project:
  base_dir: .
  output_dir: build/output
  temp_dir: build/tmp

ai:
  provider: mock

workflow:
  actions:
    - id: gen_with_kb
      type: generative
      returns: text
      prompt: "Fornisci un sommario dei documenti: {{kb_text}}"
      kb:
        enabled: true
        paths: ["kb/*.md", "kb/*.pdf"]
        strategy: inline
        as_text: true
        upload: false
        max_chars: 10000
    - id: gen_with_upload
      type: generative
      returns: text
      prompt: "Analizza i documenti caricati"
      kb:
        enabled: true
        paths: ["kb/*.pdf"]
        strategy: upload
        upload: true
        as_text: false
        mime_type: "application/pdf"

  templates:
    - path: templates/demo_template.docx
      adapter: docx
      placeholder_map:
        summary: gen_with_kb
        remote_note: gen_with_upload
